# The version of Kubernetes the cluster is running
kubernetes:
  version: "1.9"

# The cluster namespace used for the services
namespace: api-builder

# Use cached images if present
#pullPolicy: IfNotPresent
pullPolicy: Always

# MySQL Configuration
mysql:
  replicaCount: 1
  image: gcr.io/rd-api-builder/axway/api-builder-v4-demo-mysql

# Mongo Configuration
mongo:
  replicaCount: 1
  image: gcr.io/rd-api-builder/axway/api-builder-v4-demo-mongo

# Review-Service Configuration
review:
  apikey: my-review-secret-apikey
  replicaCount: 1
  image: gcr.io/rd-api-builder/axway/api-builder-v4-demo-review
  db:
    user: root
    password: password

# Product-Service Configuration
product:
  apikey: my-product-secret-apikey
  replicaCount: 1
  image: gcr.io/rd-api-builder/axway/api-builder-v4-demo-product
  db:
    user: root
    password: password