version: '3'
services:
  mongo:
    image: "axway/api-builder-v4-demo-mongo"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=apibuilder
      - MONGO_INITDB_ROOT_PASSWORD=apibuilder
      - MONGO_INITDB_DATABASE=admin

  mysql:
    image: "axway/api-builder-v4-demo-mysql"
    environment:
      - MYSQL_DATABASE=productdb
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=apibuilder
      - MYSQL_PASSWORD=apibuilder
