{{if eq .Values.kubernetes.version "1.9"}}
apiVersion: apps/v1
{{ else }}
apiVersion: apps/v1beta2
{{end}}
kind: Deployment
metadata:
  name: {{ .Release.Name }}-product
  namespace: {{ .Values.namespace }}
  labels:
    app: product
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.product.replicaCount }}
  selector:
    matchLabels:
      app: product
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: product
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: product
          imagePullPolicy: {{ .Values.pullPolicy }}
          image: {{ .Values.product.image }}
          env:
            - name: APIKEY
              value: {{ .Values.product.apikey }}
            - name: MYSQL_HOST
              value: {{ .Release.Name }}-mysql.{{ .Values.namespace }}
            - name: MYSQL_USER
              value: {{ .Values.product.db.user }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.product.db.password }}
          ports:
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /apibuilderPing.json
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /apibuilderPing.json
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
